#!/bin/bash

. test.common

test_start "ptp4l master selection (clockClass, priority1, priority2)" 

master_nodes="2"

master_conf="clockClass 6"
slave_conf=""
run_ptp4l || test_fail
check_sync || test_fail

master_conf=""
slave_conf="clockClass 249"
run_ptp4l || test_fail
check_sync || test_fail

master_conf="priority1 127"
slave_conf=""
run_ptp4l || test_fail
check_sync || test_fail

master_conf=""
slave_conf="priority2 129"
run_ptp4l || test_fail
check_sync || test_fail

test_pass
