#!/bin/bash

. test.common

test_start "ptp4l with late master reselect"

master_start=100.0
slave_start=0.0
slave_conf="logging_level 7
pi_offset_const 0.05"
min_sync_time=110
max_sync_time=140

run_ptp4l || test_fail
check_sync || test_fail
check_ptp4l_delay || test_fail

test_pass
