#!/bin/bash

. test.common

test_start "ptp4l with large frequency offsets"

max_sync_time=80

freq_offset=$(awk 'BEGIN { print 1 / 0.91 - 1 }')
run_ptp4l || test_fail
check_sync || test_fail

freq_offset=$(awk 'BEGIN { print 1 / 1.09 - 1 }')
run_ptp4l || test_fail
check_sync || test_fail

test_pass
