#!/bin/bash

. test.common

test_start "ptp4l with large initial offsets"

time_offset=1e9
run_ptp4l || test_fail
check_sync || test_fail

time_offset=-1e9
run_ptp4l || test_fail
check_sync || test_fail

test_pass
