#!/bin/bash

. test.common

test_start "ptp4l with various sync intervals"

max_sync_time=300

for i in $(seq -4 2 4); do
	update_interval=$i
	master_conf="logSyncInterval $i"
	run_ptp4l || test_fail
	check_sync || test_fail
done

test_pass
