#!/bin/bash

. test.common

test_start "phc2sys"

nodes=1
master_nodes="0"
phc2sys_node=1
phc2sys_conf="-O 0 -s /dev/ptp0"

run_test || test_fail
check_sync || test_fail

time_max_limit=1e-8
phc2sys_conf="-O 0 -s /dev/ptp0 -d /dev/pps0"

run_test || test_fail
check_sync || test_fail

test_pass
