#!/bin/bash

. test.common

test_start "ptp4l with boundary clocks"

# 1 --- 2 --- 3
#       |     |
#       4 --- 5 --- 6,7
subnets="1 2 | 2 3 | 2 4 | 3 5 | 4 5 | 5 6 7"
nodes=7
max_sync_time=100
master_conf="clockClass 6"

for master_node in 1 4 7; do
	run_ptp4l || test_fail
	check_sync || test_fail
done

test_pass
