#!/bin/bash

. test.common

test_start "ptp4l with external clock step"

# start the master so that the slaves are likely to have
# the step between the sync and delay request messages
freq_offset=0.0
master_start=0.9
# 100s step in 100th second
slave_step="(* 100 (equal 0.1 (sum 1.0) 100))"
min_sync_time=100
max_sync_time=110
nodes=6

slave_conf="clock_servo pi
delay_filter_length 20
step_threshold 10.0"
run_ptp4l || test_fail
check_sync || test_fail

slave_conf="clock_servo linreg
delay_filter_length 20
step_threshold 10.0"
run_ptp4l || test_fail
check_sync || test_fail

test_pass
