#!/bin/bash

. test.common

test_start "ptp4l with various base delays"

max_sync_time=320
update_interval=-4
master_conf="logSyncInterval -4
	     logMinDelayReqInterval -4"

for i in $(seq -7 1 -1); do
	base_delay=$(awk 'BEGIN {print 1e'$i'}')
	run_ptp4l || test_fail
	check_sync || test_fail
done

test_pass
