#!/bin/bash

. test.common

test_start "ptp4l with leap second"

export CLKNETSIM_START_DATE=$(TZ=UTC date -d 'Dec 31 2030 0:00:00' +'%s')

limit=$[30 * 3600]
leap_start=$[24 * 3600]
min_sync_time=$[$leap_start - 1]
max_sync_time=$[$leap_start]
utc_offset=37
time_rms_limit=1e-4
time_max_limit=1e-3

master_conf="logAnnounceInterval 10
logSyncInterval 10
logMinDelayReqInterval 10"
slave_conf="$master_conf
time_stamping software
clock_servo linreg"

pmc_node=3
pmc_uds="1:1"
pmc_start=$[12 * 3600]

for leap in "+1" "-1"; do
	case $leap in
		+1)
			leap_conf="leap61 1 leap59 0"
			;;
		-1)
			leap_conf="leap61 0 leap59 1"
			;;
	esac

	master_step="(* $[$utc_offset + $leap] (equal 0.1 (sum 1.0) 1))"
	pmc_conf="SET GRANDMASTER_SETTINGS_NP clockClass 6 clockAccuracy 0xfe offsetScaledLogVariance 0xffff currentUtcOffset $utc_offset $leap_conf currentUtcOffsetValid 1 ptpTimescale 1 timeTraceable 1 frequencyTraceable 1 timeSource 0xa1"

	run_ptp4l || test_fail
	check_sync || test_fail
done

test_pass
