#!/bin/bash

. test.common

test_start "ptp4l with UDPv6 transport"

export CLKNETSIM_IP_FAMILY=0
master_conf="network_transport UDPv6"
slave_conf="network_transport UDPv6"

run_ptp4l || test_fail
check_sync || test_fail

test_pass
